version: '3' #第三个版本
services:
  MS:
    image: aoian5173/hadoop5173:latest
    command: ./start-hadoop.sh
    container_name: hadoop-master
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
      - HADOOP_HOME=/usr/local/hadoop
    privileged: true
    ports:
      - 8088:8088
      - 50070:50070
    networks:
      hadoop:
        ipv4_address: 172.10.10.10
  S1:
    image: aoian5173/hadoop5173:latest
    container_name: hadoop-slave1
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
      - HADOOP_HOME=/usr/local/hadoop
    privileged: true
    networks:
      hadoop:
  S2:
    image: aoian5173/hadoop5173:latest
    container_name: hadoop-slave2
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
      - HADOOP_HOME=/usr/local/hadoop
    privileged: true
    networks:
      hadoop:
networks:
  hadoop:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.10.0/24
          gateway: 172.10.10.1
          
