version: '3' #第三个版本
services:
  MS:
    image: kiwenlau/hadoop:1.0
    command: ./start-hadoop.sh
    container_name: hadoop-master
    privileged: true
    ports:
      - 8088:8088
      - 50070:50070
    networks:
      hadoop:
        ipv4_address: 172.10.10.10
  S1:
    image: kiwenlau/hadoop:1.0
    container_name: hadoop-slave
    privileged: true
    networks:
      hadoop:
  S2:
    image: kiwenlau/hadoop:1.0
    container_name: hadoop-slave
    privileged: true
    networks:
      hadoop:
networks:
  hadoop:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.10.0/24
          gateway: 172.10.10.1
